name: Daily Platform Report CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'daily-platform-report/**'
      - '.github/workflows/daily-platform-report-ci.yaml'

env:
  PROJECT_ID: "project-18ee516c-a108-431d-a73"
  REGION: asia-south1

  REPOSITORY: platform-automation-repo
  IMAGE_NAME: daily-platform-report

  IMAGE_TAG: ${{ github.sha }}

permissions:
  id-token: write
  contents: read

jobs:

  build-and-push:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/440909314761/locations/global/workloadIdentityPools/platform-github-pool/providers/github-provider
          service_account: github-actions@project-18ee516c-a108-431d-a73.iam.gserviceaccount.com
          token_format: access_token
          
      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker
        run: |
          gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      - name: Build Docker Image
        working-directory: ./daily-platform-report
        run: |
          docker build \
            -t $IMAGE_NAME:$IMAGE_TAG \
            .

      - name: Tag Docker Image
        run: |
          docker tag \
            $IMAGE_NAME:$IMAGE_TAG \
            $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

      - name: Push Docker Image
        run: |
          docker push \
            $REGION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE_NAME:$IMAGE_TAG

      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: stackcouture/gitops-microservices-platform
          token: ${{ secrets.GITOPS_TOKEN }}
          fetch-depth: 0

      - name: Install Kustomize
        run: |
          KUSTOMIZE_VERSION=v5.4.2

          curl -sLo kustomize.tar.gz \
          https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz

          tar -xzf kustomize.tar.gz

          chmod +x kustomize
          sudo mv kustomize /usr/local/bin/

          kustomize version
      - name: Debug
        run: |
          echo "IMAGE_TAG=${IMAGE_TAG}"

      - name: Update Image Tag
        run: |
          cd automation/daily-platform-report/overlays/dev

          kustomize edit set image \
          asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/platform-automation-repo/daily-platform-report=asia-south1-docker.pkg.dev/project-18ee516c-a108-431d-a73/platform-automation-repo/daily-platform-report:${IMAGE_TAG}
      
      - name: Verify
        run: |
          cat automation/daily-platform-report/overlays/dev/kustomization.yaml

      - name: Commit Changes and Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add automation/daily-platform-report/overlays/dev/kustomization.yaml
          git commit -m "chore(daily-worker-report): update image to ${IMAGE_TAG}" || exit 0
          git push
